### ISSUE TITLE
Clicking the links on the meta-analysis page takes me to a youtube video rather than the OSF link

### ISSUE THREAD

**Issue by mnoetel** [Motivation-and-Behaviour/screen_umbrella#11]
Association between TV programs and movies: General and Sleep: Duration

This association is based on the findings of 42 studies, which collected data on 3807 participants.
Original meta-analysis: Abraham 2020; 10.31219/osf.io/c59v3

Points to: [10.31219/osf.io/c59v3](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by tarensanders** [comment]
😉
It's all fake data in the viz. Just wanted to check that embedding hyperlinks in the popup modal works.
